"""M3 autogenerate pipeline: desired snapshot, diff, emit, end-to-end CLI."""

import sys

import pytest

from stint import StateFile
from stint.autogen.desired import build_desired_snapshot
from stint.autogen.diff import (
    AddCustomFieldOption,
    CreateCustomField,
    CreateIssueTypeScreenScheme,
    CreateProject,
    CreateScreen,
    CreateScreenScheme,
    DeleteCustomField,
    RemoveCustomFieldOption,
    SetProjectIssueTypeScreenScheme,
    UpdateCustomField,
    diff,
)
from stint.autogen.emit import render_autogenerated, sort_changes
from stint.fields import SelectField, TextField
from stint.registry import registry
from stint.state.file import (
    CustomFieldMapping,
)
from stint.state.snapshot import (
    CustomFieldSnapshot,
    ServerInfoSnapshot,
    Snapshot,
)


# ── Helpers ──────────────────────────────────────────────────────────
@pytest.fixture(autouse=True)
def _isolate_registry():
    """Each test gets a clean registry. The platform example registers things
    at import time; tests that need it re-import after clearing."""
    registry.reset()
    sys.modules.pop("examples.platform", None)
    yield
    registry.reset()
    sys.modules.pop("examples.platform", None)


def _empty_snapshot() -> Snapshot:
    return Snapshot(
        server_info=ServerInfoSnapshot(deployment_type="Server", version="9", base_url="x"),
    )


# ── Desired snapshot ─────────────────────────────────────────────────
def test_desired_snapshot_derives_itss_and_fcs_per_project():
    """Importing the example schema produces a desired snapshot with a
    synthesized ITSS named `{key}_itss` and FCS named `{key}_fcs`."""
    import examples.platform  # noqa: F401  -- import-for-side-effects

    desired = build_desired_snapshot()
    assert "bug_severity" in desired.custom_fields
    assert "bug" in desired.issuetypes
    assert "PLAT" in desired.projects
    # Derived schemes:
    assert "PLAT_itss" in desired.issuetype_screen_schemes
    assert "PLAT_fcs" in desired.field_configuration_schemes
    itss = desired.issuetype_screen_schemes["PLAT_itss"]
    assert itss.mappings["default"] == "bug_screens"
    assert itss.mappings["bug"] == "bug_screens"
    fcs = desired.field_configuration_schemes["PLAT_fcs"]
    assert fcs.mappings["default"] == "bug_fields"


def test_desired_snapshot_derives_issuetype_scheme_per_project():
    """A project's __issuetypes__ feeds a per-project IssueTypeScheme.
    Default issuetype = first standard (non-subtask). Project records the
    binding via DesiredProject.issuetype_scheme."""
    import examples.platform  # noqa: F401

    desired = build_desired_snapshot()
    assert "PLAT_its" in desired.issuetype_schemes
    its = desired.issuetype_schemes["PLAT_its"]
    assert its.name == "PLAT Issue Type Scheme"
    assert its.issuetypes == ("bug",)
    assert its.default_issuetype == "bug"
    assert desired.projects["PLAT"].issuetype_scheme == "PLAT_its"


def test_desired_screen_carries_one_tab_with_field_refs():
    import examples.platform  # noqa: F401

    desired = build_desired_snapshot()
    edit = desired.screens["bug_edit"]
    assert len(edit.tabs) == 1
    tab = edit.tabs[0]
    assert tab.name == "Fields"
    # CustomField refs resolve to aliases; system names pass through.
    assert "Summary" in tab.field_refs
    assert "bug_severity" in tab.field_refs


# ── Diff: greenfield (no state, no Jira) ─────────────────────────────
def test_diff_greenfield_emits_create_for_every_declared_object():
    """State empty, Jira empty, schema has everything → all creates."""
    import examples.platform  # noqa: F401

    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    result = diff(
        desired=desired,
        snapshot=_empty_snapshot(),
        state=state,
        allow_delete=False,
    )
    kinds = {type(c).__name__ for c in result.changes}
    # Spot check the must-haves:
    assert "CreateCustomField" in kinds
    assert "CreateIssueType" in kinds
    assert "CreateFieldConfiguration" in kinds
    assert "CreateScreen" in kinds
    assert "CreateScreenScheme" in kinds
    assert "CreateIssueTypeScheme" in kinds
    assert "CreateIssueTypeScreenScheme" in kinds
    assert "CreateFieldConfigurationScheme" in kinds
    assert "CreateProject" in kinds
    assert "SetProjectIssueTypeScheme" in kinds
    assert "SetProjectIssueTypeScreenScheme" in kinds
    assert "SetProjectFieldConfigurationScheme" in kinds


def test_diff_greenfield_emits_no_deletes():
    import examples.platform  # noqa: F401

    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    result = diff(
        desired=desired,
        snapshot=_empty_snapshot(),
        state=state,
        allow_delete=True,
    )
    assert not any("Delete" in type(c).__name__ for c in result.changes)


# ── Diff: in-sync ────────────────────────────────────────────────────
def test_diff_in_sync_is_empty():
    """If state matches Jira and schema declares only what's already there,
    diff is empty."""
    desired = build_desired_snapshot()  # empty registry
    state = StateFile(env="dev", jira_url="x")
    result = diff(
        desired=desired,
        snapshot=_empty_snapshot(),
        state=state,
        allow_delete=False,
    )
    assert result.changes == []


# ── Diff: state-only objects (deletes) ───────────────────────────────
def test_diff_state_only_without_allow_delete_warns():
    """State has an alias the schema doesn't declare; without --allow-delete,
    diff emits a warning but no Change."""
    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    state.custom_fields["orphan"] = CustomFieldMapping(id="customfield_99999")
    result = diff(
        desired=desired,
        snapshot=_empty_snapshot(),
        state=state,
        allow_delete=False,
    )
    assert not any(isinstance(c, DeleteCustomField) for c in result.changes)
    assert any("orphan" in w for w in result.warnings)


def test_diff_state_only_with_allow_delete_emits_delete():
    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    state.custom_fields["orphan"] = CustomFieldMapping(id="customfield_99999")
    result = diff(
        desired=desired,
        snapshot=_empty_snapshot(),
        state=state,
        allow_delete=True,
    )
    assert any(isinstance(c, DeleteCustomField) and c.alias == "orphan" for c in result.changes)


# ── Diff: option changes on existing custom field ────────────────────
def test_diff_option_added_emits_add_custom_field_option():
    """Existing custom field in state with options [S1,S2]; schema declares
    [S1,S2,S3]. Diff emits AddCustomFieldOption for S3."""
    from stint.fields import CustomField

    CustomField(
        alias="bug_severity",
        name="Severity",
        type=SelectField,
        options=["S1", "S2", "S3"],
    )
    desired = build_desired_snapshot()

    state = StateFile(env="dev", jira_url="x")
    state.custom_fields["bug_severity"] = CustomFieldMapping(
        id="customfield_10042",
        options={"S1": "100", "S2": "101"},
    )
    snap = _empty_snapshot()
    snap.custom_fields["customfield_10042"] = CustomFieldSnapshot(
        id="customfield_10042",
        name="Severity",
        type_id=SelectField.jira_type_id,
        options={"S1": "100", "S2": "101"},
    )
    result = diff(desired=desired, snapshot=snap, state=state, allow_delete=False)
    adds = [c for c in result.changes if isinstance(c, AddCustomFieldOption)]
    assert len(adds) == 1
    assert adds[0].value == "S3"


def test_diff_option_removed_requires_allow_delete():
    """Existing field has [S1,S2]; schema has [S1]. Without --allow-delete:
    warning. With: RemoveCustomFieldOption."""
    from stint.fields import CustomField

    CustomField(
        alias="bug_severity",
        name="Severity",
        type=SelectField,
        options=["S1"],
    )
    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    state.custom_fields["bug_severity"] = CustomFieldMapping(
        id="customfield_10042",
        options={"S1": "100", "S2": "101"},
    )
    snap = _empty_snapshot()
    snap.custom_fields["customfield_10042"] = CustomFieldSnapshot(
        id="customfield_10042",
        name="Severity",
        type_id=SelectField.jira_type_id,
        options={"S1": "100", "S2": "101"},
    )

    no_delete = diff(desired=desired, snapshot=snap, state=state, allow_delete=False)
    assert not any(isinstance(c, RemoveCustomFieldOption) for c in no_delete.changes)
    assert any("S2" in w for w in no_delete.warnings)

    with_delete = diff(desired=desired, snapshot=snap, state=state, allow_delete=True)
    removes = [c for c in with_delete.changes if isinstance(c, RemoveCustomFieldOption)]
    assert len(removes) == 1
    assert removes[0].value == "S2"


# ── Diff: rename ─────────────────────────────────────────────────────
def test_diff_emits_update_for_renamed_custom_field():
    from stint.fields import CustomField

    CustomField(alias="bug_severity", name="Severity (renamed)", type=TextField)
    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    state.custom_fields["bug_severity"] = CustomFieldMapping(
        id="customfield_10042",
    )
    snap = _empty_snapshot()
    snap.custom_fields["customfield_10042"] = CustomFieldSnapshot(
        id="customfield_10042",
        name="Severity",
        type_id=TextField.jira_type_id,
    )
    result = diff(desired=desired, snapshot=snap, state=state, allow_delete=False)
    updates = [c for c in result.changes if isinstance(c, UpdateCustomField)]
    assert len(updates) == 1
    assert updates[0].alias == "bug_severity"
    assert updates[0].name == "Severity (renamed)"


# ── Diff: drift ──────────────────────────────────────────────────────
def test_diff_warns_on_state_id_missing_from_jira():
    """State references customfield_99999 but Jira doesn't have it.
    Warning emitted; no Change."""
    from stint.fields import CustomField

    CustomField(alias="bug_severity", name="Severity", type=TextField)
    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    state.custom_fields["bug_severity"] = CustomFieldMapping(id="customfield_99999")
    result = diff(
        desired=desired,
        snapshot=_empty_snapshot(),
        state=state,
        allow_delete=False,
    )
    assert any("not present in Jira" in w for w in result.warnings)


def test_diff_emits_set_scheme_for_existing_project_with_drifted_binding():
    """Issue #5: an existing project whose actual scheme bindings differ
    from what the schema declares should emit SetProject*Scheme. The desired
    schemes must already be in state — otherwise the create-side change owns
    the binding (and this code path skips them)."""
    import examples.platform  # noqa: F401
    from stint.autogen.diff import (
        SetProjectFieldConfigurationScheme,
        SetProjectIssueTypeScheme,
    )
    from stint.state.file import ProjectMapping, SimpleMapping
    from stint.state.snapshot import ProjectSnapshot

    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    # Project + schemes all already in state. ITSS matches what's on Jira,
    # so it should NOT be re-bound. IssueTypeScheme + FCS are in state but
    # the snapshot shows the project bound to *different* scheme ids.
    state.projects["PLAT"] = ProjectMapping(id="p-1", key="PLAT")
    state.issuetype_schemes["PLAT_its"] = SimpleMapping(id="its-want")
    state.issuetype_screen_schemes["PLAT_itss"] = SimpleMapping(id="itss-want")
    state.field_configuration_schemes["PLAT_fcs"] = SimpleMapping(id="fcs-want")
    snapshot = Snapshot(
        server_info=ServerInfoSnapshot(deployment_type="Server", version="9", base_url="x"),
        projects={
            "PLAT": ProjectSnapshot(
                id="p-1",
                key="PLAT",
                name="Platform",
                lead="cturner",
                project_type_key="software",
                style="classic",
                issuetype_scheme_id="its-other",  # drift!
                issuetype_screen_scheme_id="itss-want",  # in sync
                field_configuration_scheme_id=None,  # never bound
            ),
        },
    )
    result = diff(desired=desired, snapshot=snapshot, state=state, allow_delete=False)
    kinds = {type(c).__name__ for c in result.changes}
    assert "SetProjectIssueTypeScheme" in kinds
    assert "SetProjectFieldConfigurationScheme" in kinds
    # In-sync ITSS produces no rebind.
    set_itss = [c for c in result.changes if isinstance(c, SetProjectIssueTypeScreenScheme)]
    assert set_itss == []
    # The two emitted rebinds reference the right project + scheme aliases.
    its_change = next(c for c in result.changes if isinstance(c, SetProjectIssueTypeScheme))
    assert its_change.project_alias == "PLAT" and its_change.scheme_alias == "PLAT_its"
    fcs_change = next(c for c in result.changes if isinstance(c, SetProjectFieldConfigurationScheme))
    assert fcs_change.project_alias == "PLAT" and fcs_change.scheme_alias == "PLAT_fcs"


def test_diff_skips_set_scheme_when_desired_alias_not_yet_in_state():
    """When the desired scheme is *also* being created in this migration
    (so its alias isn't in state yet), the create-side change owns the
    binding. The existing-project rebind must not also fire — otherwise
    the migration would call set_project_*_scheme before state has the
    new scheme's id."""
    import examples.platform  # noqa: F401
    from stint.state.file import ProjectMapping
    from stint.state.snapshot import ProjectSnapshot

    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    state.projects["PLAT"] = ProjectMapping(id="p-1", key="PLAT")
    # Note: state.issuetype_schemes etc. are intentionally empty.
    snapshot = Snapshot(
        server_info=ServerInfoSnapshot(deployment_type="Server", version="9", base_url="x"),
        projects={
            "PLAT": ProjectSnapshot(
                id="p-1",
                key="PLAT",
                name="Platform",
                lead="cturner",
                project_type_key="software",
                style="classic",
            ),
        },
    )
    result = diff(desired=desired, snapshot=snapshot, state=state, allow_delete=False)
    kinds = {type(c).__name__ for c in result.changes}
    assert "SetProjectIssueTypeScheme" not in kinds
    assert "SetProjectIssueTypeScreenScheme" not in kinds
    assert "SetProjectFieldConfigurationScheme" not in kinds


# ── Sort ─────────────────────────────────────────────────────────────
def test_sort_orders_phases_correctly():
    """A jumbled change list comes out phase-ordered: fields before screens,
    screens before screen schemes, schemes before projects, project bindings last."""
    changes = [
        SetProjectIssueTypeScreenScheme(project_alias="p", scheme_alias="i"),
        CreateProject(
            alias="p",
            key="P",
            name="P",
            project_type_key="software",
            lead="x",
            description="",
        ),
        CreateCustomField(
            alias="cf",
            name="CF",
            type_id=TextField.jira_type_id,
            description="",
            options=(),
        ),
        CreateScreen(alias="s", name="S", description=""),
        CreateScreenScheme(
            alias="ss",
            name="SS",
            description="",
            screens={"default": "s"},
        ),
        CreateIssueTypeScreenScheme(
            alias="itss",
            name="ITSS",
            description="",
            mappings={"default": "ss"},
        ),
    ]
    sorted_changes = sort_changes(changes)
    order = [type(c).__name__ for c in sorted_changes]
    # Phase order: CF, Screen, ScreenScheme, ITSS, Project, SetProjectITSS
    assert order == [
        "CreateCustomField",
        "CreateScreen",
        "CreateScreenScheme",
        "CreateIssueTypeScreenScheme",
        "CreateProject",
        "SetProjectIssueTypeScreenScheme",
    ]


# ── Emit: generated file is loadable ─────────────────────────────────
def test_emit_generated_file_loads_via_migration_loader(tmp_path):
    """The full pipeline produces a file the migration loader accepts."""
    changes = [
        CreateCustomField(
            alias="bug_severity",
            name="Severity",
            type_id=SelectField.jira_type_id,
            description="bug severity",
            options=("S1", "S2", "S3", "S4"),
        ),
    ]
    source = render_autogenerated(
        "create severity",
        parents=None,
        revision="abcdef012345",
        changes=changes,
    )
    p = tmp_path / "2026_05_20_1200_create_severity.py"
    p.write_text(source)

    from stint import load_migrations

    graph = load_migrations(tmp_path)
    m = graph.by_revision["abcdef012345"]
    assert m.down_revision is None
    # The body is callable; running it via a context will hit the dialect,
    # but at least the bytecode compiled.


def test_emit_imports_selectfield_only_when_used():
    """SelectField appears in imports when a select-type CF is created;
    not otherwise."""
    src_select = render_autogenerated(
        "x",
        parents=None,
        revision="r",
        changes=[
            CreateCustomField(
                alias="a",
                name="A",
                type_id=SelectField.jira_type_id,
                description="",
                options=("X",),
            )
        ],
    )
    assert "from stint.fields import SelectField" in src_select

    src_text = render_autogenerated(
        "x",
        parents=None,
        revision="r",
        changes=[
            CreateCustomField(
                alias="a",
                name="A",
                type_id=TextField.jira_type_id,
                description="",
                options=(),
            )
        ],
    )
    assert "from stint.fields import TextField" in src_text
    assert "SelectField" not in src_text


def test_emit_downgrade_always_op_unsupported():
    """Per policy, generated downgrades are op.unsupported."""
    src = render_autogenerated(
        "x",
        parents=None,
        revision="r",
        changes=[
            CreateCustomField(
                alias="a",
                name="A",
                type_id=TextField.jira_type_id,
                description="",
                options=(),
            )
        ],
    )
    assert "op.unsupported(" in src
    assert "async def downgrade()" in src


# ── End-to-end: autogenerate against the platform example ────────────
@pytest.mark.asyncio
async def test_autogenerate_end_to_end_via_python_api(tmp_path):
    """Without going through CLI: load schema, build desired, diff against
    empty Jira, render — the output compiles and reloads cleanly."""
    import examples.platform  # noqa: F401

    desired = build_desired_snapshot()
    state = StateFile(env="dev", jira_url="x")
    result = diff(
        desired=desired,
        snapshot=_empty_snapshot(),
        state=state,
        allow_delete=False,
    )
    assert result.changes
    src = render_autogenerated(
        "stand up platform",
        parents=None,
        revision="cafebabe1234",
        changes=result.changes,
    )
    p = tmp_path / "2026_05_20_1200_stand_up_platform.py"
    p.write_text(src)
    from stint import load_migrations

    graph = load_migrations(tmp_path)
    assert "cafebabe1234" in graph.by_revision
