"""Render Change records (or empty stubs) into Python migration file source.

Output is always a complete, importable Python module that satisfies the
migration loader's contract: module-level `revision`, `down_revision`,
`async def upgrade()`, `async def downgrade()`.

Downgrade policy: autogenerated migrations always emit
``op.unsupported(...)`` in their downgrade body. Alembic-style auto-downgrade
is notoriously unreliable (updates can't be auto-inverted without before-state;
deletes can't be auto-restored). The honest move is to refuse and let the
author write the inverse explicitly when they need it.
"""

from __future__ import annotations

import re
import secrets
from datetime import datetime, timezone
from typing import Any

from stint.autogen.diff import (
    AddCustomFieldOption,
    AddScreenTab,
    AddScreenTabField,
    Change,
    CreateCustomField,
    CreateFieldConfiguration,
    CreateFieldConfigurationScheme,
    CreateIssueType,
    CreateIssueTypeScheme,
    CreateIssueTypeScreenScheme,
    CreateProject,
    CreateScreen,
    CreateScreenScheme,
    DeleteCustomField,
    DeleteFieldConfiguration,
    DeleteFieldConfigurationScheme,
    DeleteIssueType,
    DeleteIssueTypeScheme,
    DeleteIssueTypeScreenScheme,
    DeleteProject,
    DeleteScreen,
    DeleteScreenScheme,
    RemoveCustomFieldOption,
    SetFieldConfigurationItem,
    SetProjectFieldConfigurationScheme,
    SetProjectIssueTypeScheme,
    SetProjectIssueTypeScreenScheme,
    UpdateCustomField,
    UpdateFieldConfigurationScheme,
    UpdateIssueType,
    UpdateIssueTypeScheme,
    UpdateIssueTypeScreenScheme,
    UpdateProject,
    UpdateScreen,
    UpdateScreenScheme,
)
from stint.fields import (
    DateField,
    DateTimeField,
    MultiSelectField,
    NumberField,
    SelectField,
    TextAreaField,
    TextField,
    UserField,
    _FieldType,
)

REVISION_ID_BYTES = 6  # 12 hex chars, plenty unique per project


def new_revision_id() -> str:
    """12-char hex id. Same length as Alembic's."""
    return secrets.token_hex(REVISION_ID_BYTES)


def new_filename(message: str, when: datetime | None = None) -> str:
    """`YYYY_MM_DD_HHMM_slug.py`. Slug derived from `message`."""
    when = when or datetime.now(timezone.utc)
    slug = _slugify(message)
    return f"{when:%Y_%m_%d_%H%M}_{slug}.py"


def _slugify(message: str) -> str:
    s = re.sub(r"[^\w\s-]", "", message.strip().lower())
    s = re.sub(r"[\s-]+", "_", s)
    return s.strip("_")[:60] or "migration"


def _format_parents(parents: tuple[str, ...] | None) -> str:
    if parents is None or len(parents) == 0:
        return "None"
    if len(parents) == 1:
        return repr(parents[0])
    return "(" + ", ".join(repr(p) for p in parents) + ")"


def render_empty(
    message: str,
    *,
    parents: tuple[str, ...] | None,
    revision: str | None = None,
) -> str:
    revision = revision or new_revision_id()
    return f'''"""{message}

Created: {datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S UTC}
"""

revision = {revision!r}
down_revision = {_format_parents(parents)}


async def upgrade() -> None:
    pass


async def downgrade() -> None:
    pass
'''


def render_merge(
    message: str,
    *,
    parents: tuple[str, ...],
    revision: str | None = None,
) -> str:
    if len(parents) < 2:
        raise ValueError(f"render_merge: parents must have at least 2 revisions, got {parents!r}")
    revision = revision or new_revision_id()
    return f'''"""Merge {", ".join(p[:8] for p in parents)}: {message}

Created: {datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S UTC}

This is a merge migration. It joins the listed parent revisions into a single
head so future migrations can be linear again. Bodies are typically empty;
add reconciliation ops only if the branches you are merging have made
conflicting changes that need explicit resolution.
"""

revision = {revision!r}
down_revision = {_format_parents(parents)}


async def upgrade() -> None:
    pass


async def downgrade() -> None:
    pass
'''


def render_autogenerated(
    message: str,
    *,
    parents: tuple[str, ...] | None,
    revision: str,
    changes: list[Change],
) -> str:
    """Phase-sorted op calls. Downgrade body is a single op.unsupported."""
    sorted_changes = sort_changes(changes)
    body_lines = _render_upgrade_body(sorted_changes)
    imports = _render_imports(sorted_changes)
    affected = sorted({_affected_alias(c) for c in sorted_changes if _affected_alias(c)})
    affected_str = ", ".join(repr(a) for a in affected) or "(none)"
    return f'''"""{message}

Created: {datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S UTC}
Generated by `stint revision --autogenerate`.

Affected aliases: {affected_str}
"""

{imports}

revision = {revision!r}
down_revision = {_format_parents(parents)}


async def upgrade() -> None:
{body_lines}


async def downgrade() -> None:
    op.unsupported(
        "Auto-generated migration: write your own downgrade ops if you need "
        "to roll back this change."
    )
'''


# ── Sort ─────────────────────────────────────────────────────────────
# Phase: lower runs first. Within a phase, sort by affected alias.
_PHASE: dict[type, int] = {
    CreateCustomField: 10,
    CreateIssueType: 11,
    CreateFieldConfiguration: 12,
    CreateScreen: 13,
    AddScreenTab: 20,
    AddScreenTabField: 21,
    SetFieldConfigurationItem: 22,
    CreateScreenScheme: 30,
    CreateIssueTypeScheme: 39,
    CreateIssueTypeScreenScheme: 40,
    CreateFieldConfigurationScheme: 41,
    CreateProject: 50,
    SetProjectIssueTypeScheme: 59,
    SetProjectIssueTypeScreenScheme: 60,
    SetProjectFieldConfigurationScheme: 61,
    UpdateCustomField: 70,
    AddCustomFieldOption: 71,
    RemoveCustomFieldOption: 72,
    UpdateIssueType: 73,
    UpdateScreen: 74,
    UpdateScreenScheme: 75,
    UpdateIssueTypeScheme: 75,
    UpdateIssueTypeScreenScheme: 76,
    UpdateFieldConfigurationScheme: 77,
    UpdateProject: 78,
    DeleteProject: 80,
    DeleteIssueTypeScheme: 80,
    DeleteIssueTypeScreenScheme: 81,
    DeleteFieldConfigurationScheme: 82,
    DeleteScreenScheme: 83,
    DeleteScreen: 84,
    DeleteFieldConfiguration: 85,
    DeleteIssueType: 86,
    DeleteCustomField: 87,
}


def sort_changes(changes: list[Change]) -> list[Change]:
    """Stable sort by (phase, affected_alias). Ties preserve input order."""
    indexed = list(enumerate(changes))
    indexed.sort(
        key=lambda i_c: (
            _PHASE.get(type(i_c[1]), 99),
            _affected_alias(i_c[1]) or "",
            i_c[0],
        )
    )
    return [c for _, c in indexed]


def _affected_alias(change: Change) -> str | None:
    for attr in ("alias", "screen_alias", "fc_alias", "field_alias", "project_alias"):
        if hasattr(change, attr):
            return getattr(change, attr)
    return None


# ── Per-change renderers ─────────────────────────────────────────────
_FIELD_TYPE_BY_ID: dict[str, type[_FieldType]] = {
    cls.jira_type_id: cls
    for cls in (
        TextField,
        TextAreaField,
        SelectField,
        MultiSelectField,
        UserField,
        NumberField,
        DateField,
        DateTimeField,
    )
}


def _render_imports(changes: list[Change]) -> str:
    lines = ["from stint import op"]
    field_classes: set[str] = set()
    for c in changes:
        if isinstance(c, CreateCustomField):
            cls = _FIELD_TYPE_BY_ID.get(c.type_id)
            if cls is not None:
                field_classes.add(cls.__name__)
    if field_classes:
        lines.append(f"from stint.fields import {', '.join(sorted(field_classes))}")
    return "\n".join(lines)


def _render_upgrade_body(changes: list[Change]) -> str:
    if not changes:
        return "    pass"
    return "\n".join(_render_one(c) for c in changes)


def _render_one(change: Change) -> str:
    if isinstance(change, CreateCustomField):
        cls = _FIELD_TYPE_BY_ID.get(change.type_id)
        type_repr = cls.__name__ if cls else f'"unknown type {change.type_id}"'
        options_kv = f",\n        options={list(change.options)!r}" if change.options else ""
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_custom_field(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r},\n"
            f"        type={type_repr}{desc_kv}{options_kv},\n"
            f"    )"
        )

    if isinstance(change, UpdateCustomField):
        return _render_update(
            "update_custom_field",
            alias=change.alias,
            name=change.name,
            description=change.description,
        )

    if isinstance(change, AddCustomFieldOption):
        return (
            f"    await op.add_custom_field_option(\n"
            f"        field_alias={change.field_alias!r},\n"
            f"        value={change.value!r},\n"
            f"    )"
        )

    if isinstance(change, RemoveCustomFieldOption):
        return (
            f"    await op.remove_custom_field_option(\n"
            f"        field_alias={change.field_alias!r},\n"
            f"        value={change.value!r},\n"
            f"    )"
        )

    if isinstance(change, DeleteCustomField):
        return f"    await op.delete_custom_field(alias={change.alias!r})"

    if isinstance(change, CreateIssueType):
        subtask_kv = ",\n        subtask=True" if change.subtask else ""
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_issuetype(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r}{desc_kv}{subtask_kv},\n"
            f"    )"
        )

    if isinstance(change, UpdateIssueType):
        return _render_update(
            "update_issuetype",
            alias=change.alias,
            name=change.name,
            description=change.description,
        )

    if isinstance(change, DeleteIssueType):
        return f"    await op.delete_issuetype(alias={change.alias!r})"

    if isinstance(change, CreateScreen):
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_screen(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r}{desc_kv},\n"
            f"    )"
        )

    if isinstance(change, AddScreenTab):
        return (
            f"    await op.add_screen_tab(\n"
            f"        screen_alias={change.screen_alias!r},\n"
            f"        tab_name={change.tab_name!r},\n"
            f"    )"
        )

    if isinstance(change, AddScreenTabField):
        return (
            f"    await op.add_screen_tab_field(\n"
            f"        screen_alias={change.screen_alias!r},\n"
            f"        tab_name={change.tab_name!r},\n"
            f"        field_alias={change.field_alias!r},\n"
            f"    )"
        )

    if isinstance(change, UpdateScreen):
        return _render_update(
            "update_screen",
            alias=change.alias,
            name=change.name,
            description=change.description,
        )

    if isinstance(change, DeleteScreen):
        return f"    await op.delete_screen(alias={change.alias!r})"

    if isinstance(change, CreateScreenScheme):
        screens_str = _render_dict(change.screens)
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_screen_scheme(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r}{desc_kv},\n"
            f"        screens={screens_str},\n"
            f"    )"
        )

    if isinstance(change, UpdateScreenScheme):
        kwargs: list[str] = [f"alias={change.alias!r}"]
        if change.name is not None:
            kwargs.append(f"name={change.name!r}")
        if change.description is not None:
            kwargs.append(f"description={change.description!r}")
        if change.screens is not None:
            kwargs.append(f"screens={_render_dict(change.screens)}")
        return _kwargs_call("op.update_screen_scheme", kwargs)

    if isinstance(change, DeleteScreenScheme):
        return f"    await op.delete_screen_scheme(alias={change.alias!r})"

    if isinstance(change, CreateFieldConfiguration):
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_field_configuration(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r}{desc_kv},\n"
            f"    )"
        )

    if isinstance(change, SetFieldConfigurationItem):
        req_kv = ",\n        required=True" if change.required else ""
        hid_kv = ",\n        hidden=True" if change.hidden else ""
        return (
            f"    await op.set_field_configuration_item(\n"
            f"        fc_alias={change.fc_alias!r},\n"
            f"        field_alias={change.field_alias!r}{req_kv}{hid_kv},\n"
            f"    )"
        )

    if isinstance(change, DeleteFieldConfiguration):
        return f"    await op.delete_field_configuration(alias={change.alias!r})"

    if isinstance(change, CreateIssueTypeScheme):
        issuetypes_repr = "[" + ", ".join(repr(a) for a in change.issuetypes) + "]"
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_issuetype_scheme(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r}{desc_kv},\n"
            f"        issuetypes={issuetypes_repr},\n"
            f"        default_issuetype={change.default_issuetype!r},\n"
            f"    )"
        )

    if isinstance(change, UpdateIssueTypeScheme):
        kwargs = [f"alias={change.alias!r}"]
        if change.name is not None:
            kwargs.append(f"name={change.name!r}")
        if change.description is not None:
            kwargs.append(f"description={change.description!r}")
        if change.default_issuetype is not None:
            kwargs.append(f"default_issuetype={change.default_issuetype!r}")
        return _kwargs_call("op.update_issuetype_scheme", kwargs)

    if isinstance(change, DeleteIssueTypeScheme):
        return f"    await op.delete_issuetype_scheme(alias={change.alias!r})"

    if isinstance(change, SetProjectIssueTypeScheme):
        return (
            f"    await op.set_project_issuetype_scheme(\n"
            f"        project_alias={change.project_alias!r},\n"
            f"        scheme_alias={change.scheme_alias!r},\n"
            f"    )"
        )

    if isinstance(change, CreateIssueTypeScreenScheme):
        mappings_str = _render_dict(change.mappings)
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_issuetype_screen_scheme(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r}{desc_kv},\n"
            f"        mappings={mappings_str},\n"
            f"    )"
        )

    if isinstance(change, UpdateIssueTypeScreenScheme):
        kwargs = [f"alias={change.alias!r}"]
        if change.name is not None:
            kwargs.append(f"name={change.name!r}")
        if change.description is not None:
            kwargs.append(f"description={change.description!r}")
        if change.mappings is not None:
            kwargs.append(f"mappings={_render_dict(change.mappings)}")
        return _kwargs_call("op.update_issuetype_screen_scheme", kwargs)

    if isinstance(change, DeleteIssueTypeScreenScheme):
        return f"    await op.delete_issuetype_screen_scheme(alias={change.alias!r})"

    if isinstance(change, CreateFieldConfigurationScheme):
        mappings_str = _render_dict(change.mappings)
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_field_configuration_scheme(\n"
            f"        alias={change.alias!r},\n"
            f"        name={change.name!r}{desc_kv},\n"
            f"        mappings={mappings_str},\n"
            f"    )"
        )

    if isinstance(change, UpdateFieldConfigurationScheme):
        kwargs = [f"alias={change.alias!r}"]
        if change.name is not None:
            kwargs.append(f"name={change.name!r}")
        if change.description is not None:
            kwargs.append(f"description={change.description!r}")
        if change.mappings is not None:
            kwargs.append(f"mappings={_render_dict(change.mappings)}")
        return _kwargs_call("op.update_field_configuration_scheme", kwargs)

    if isinstance(change, DeleteFieldConfigurationScheme):
        return f"    await op.delete_field_configuration_scheme(alias={change.alias!r})"

    if isinstance(change, CreateProject):
        desc_kv = f",\n        description={change.description!r}" if change.description else ""
        return (
            f"    await op.create_project(\n"
            f"        alias={change.alias!r},\n"
            f"        key={change.key!r},\n"
            f"        name={change.name!r},\n"
            f"        project_type_key={change.project_type_key!r},\n"
            f"        lead={change.lead!r}{desc_kv},\n"
            f"    )"
        )

    if isinstance(change, SetProjectIssueTypeScreenScheme):
        return (
            f"    await op.set_project_issuetype_screen_scheme(\n"
            f"        project_alias={change.project_alias!r},\n"
            f"        scheme_alias={change.scheme_alias!r},\n"
            f"    )"
        )

    if isinstance(change, SetProjectFieldConfigurationScheme):
        return (
            f"    await op.set_project_field_configuration_scheme(\n"
            f"        project_alias={change.project_alias!r},\n"
            f"        scheme_alias={change.scheme_alias!r},\n"
            f"    )"
        )

    if isinstance(change, DeleteProject):
        return f"    await op.delete_project(\n        alias={change.alias!r},\n        key={change.key!r},\n    )"

    if isinstance(change, UpdateProject):
        kwargs = [f"alias={change.alias!r}"]
        if change.name is not None:
            kwargs.append(f"name={change.name!r}")
        if change.lead is not None:
            kwargs.append(f"lead={change.lead!r}")
        if change.description is not None:
            kwargs.append(f"description={change.description!r}")
        return _kwargs_call("op.update_project", kwargs)

    raise NotImplementedError(f"emit: no renderer for {type(change).__name__}")


def _render_update(op_name: str, *, alias: str, name: Any, description: Any) -> str:
    kwargs = [f"alias={alias!r}"]
    if name is not None:
        kwargs.append(f"name={name!r}")
    if description is not None:
        kwargs.append(f"description={description!r}")
    return _kwargs_call(f"op.{op_name}", kwargs)


def _kwargs_call(prefix: str, kwargs: list[str]) -> str:
    body = ",\n        ".join(kwargs)
    return f"    await {prefix}(\n        {body},\n    )"


def _render_dict(d: dict[str, str]) -> str:
    if not d:
        return "{}"
    items = ",\n            ".join(f"{k!r}: {v!r}" for k, v in sorted(d.items()))
    return "{\n            " + items + ",\n        }"
