"""Dialect protocol. Every backend must satisfy this contract.

The read side (detect/reflect) and the write side (the create/update/delete
surface the migration runner and session drive) are both declared here so that
callers typed against ``Dialect`` see the full method set. Concrete dialects
(see ``stint.dialects.jira``) satisfy this structurally.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Protocol

from stint.state.snapshot import Snapshot


class Dialect(Protocol):
    """The contract a backend dialect must satisfy."""

    name: str

    # ── Detection / reflection ───────────────────────────────────────
    async def detect(self) -> bool:
        """Probe the backend and return True if this dialect matches it.

        Used for auto-detection when the user did not specify a dialect at
        engine creation. The implementation should make a single cheap call
        (e.g. `GET /serverInfo`) and inspect the response.
        """

    async def reflect(self) -> Snapshot:
        """Read the current admin state from the backend into a Snapshot.

        The Snapshot is dialect-agnostic. The planner consumes it without
        needing to know which backend produced it.
        """

    # ── Custom fields ────────────────────────────────────────────────
    async def create_custom_field(
        self, *, name: str, description: str, type_id: str, searcher_key: str | None = None
    ) -> str: ...
    async def add_custom_field_option(self, field_id: str, value: str) -> str: ...
    async def delete_custom_field(self, field_id: str) -> None: ...
    async def update_custom_field(
        self, field_id: str, *, name: str | None = None, description: str | None = None, searcher_key: str | None = None
    ) -> None: ...
    async def delete_custom_field_option(self, field_id: str, option_id: str) -> None: ...

    # ── Screens ──────────────────────────────────────────────────────
    async def create_screen(self, *, name: str, description: str = "") -> str: ...
    async def delete_screen(self, screen_id: str) -> None: ...
    async def update_screen(
        self, screen_id: str, *, name: str | None = None, description: str | None = None
    ) -> None: ...
    async def add_screen_tab(self, screen_id: str, *, name: str) -> str: ...
    async def add_screen_tab_field(self, screen_id: str, tab_id: str, *, field_id: str) -> None: ...

    # ── Screen schemes ───────────────────────────────────────────────
    async def create_screen_scheme(self, *, name: str, description: str, screens: dict[str, str]) -> str: ...
    async def delete_screen_scheme(self, scheme_id: str) -> None: ...
    async def update_screen_scheme(
        self,
        scheme_id: str,
        *,
        name: str | None = None,
        description: str | None = None,
        screens: dict[str, str] | None = None,
    ) -> None: ...

    # ── Issue-type screen schemes ────────────────────────────────────
    async def create_issuetype_screen_scheme(
        self, *, name: str, description: str, mappings: list[dict[str, str]]
    ) -> str: ...
    async def delete_issuetype_screen_scheme(self, scheme_id: str) -> None: ...
    async def update_issuetype_screen_scheme(
        self, scheme_id: str, *, name: str | None = None, description: str | None = None
    ) -> None: ...
    async def set_issuetype_screen_scheme_mappings(self, scheme_id: str, *, mappings: list[dict[str, str]]) -> None: ...
    async def set_project_issuetype_screen_scheme(self, *, project_id: str, scheme_id: str) -> None: ...

    # ── Issue-type schemes ───────────────────────────────────────────
    async def create_issuetype_scheme(
        self, *, name: str, issuetype_ids: list[str], default_issuetype_id: str, description: str = ""
    ) -> str: ...
    async def update_issuetype_scheme(
        self,
        scheme_id: str,
        *,
        name: str | None = None,
        description: str | None = None,
        default_issuetype_id: str | None = None,
    ) -> None: ...
    async def delete_issuetype_scheme(self, scheme_id: str) -> None: ...
    async def set_project_issuetype_scheme(self, *, project_id: str, scheme_id: str) -> None: ...

    # ── Field configurations ─────────────────────────────────────────
    async def create_field_configuration(self, *, name: str, description: str = "") -> str: ...
    async def delete_field_configuration(self, fc_id: str) -> None: ...
    async def set_field_configuration_item(
        self, fc_id: str, *, field_id: str, required: bool = False, hidden: bool = False, description: str = ""
    ) -> None: ...
    async def create_field_configuration_scheme(self, *, name: str, description: str = "") -> str: ...
    async def delete_field_configuration_scheme(self, scheme_id: str) -> None: ...
    async def update_field_configuration_scheme(
        self, scheme_id: str, *, name: str | None = None, description: str | None = None
    ) -> None: ...
    async def set_field_configuration_scheme_mappings(
        self, scheme_id: str, *, mappings: list[dict[str, str]]
    ) -> None: ...
    async def set_project_field_configuration_scheme(self, *, project_id: str, scheme_id: str) -> None: ...

    # ── Issue types ──────────────────────────────────────────────────
    async def find_issuetype_id_by_name(self, name: str) -> str | None: ...
    async def create_issuetype(self, *, name: str, description: str = "", subtask: bool = False) -> str: ...
    async def delete_issuetype(self, issuetype_id: str) -> None: ...
    async def update_issuetype(
        self, issuetype_id: str, *, name: str | None = None, description: str | None = None
    ) -> None: ...

    # ── Projects ─────────────────────────────────────────────────────
    async def resolve_lead(self, lead: str) -> str: ...
    async def create_project(
        self,
        *,
        key: str,
        name: str,
        project_type_key: str,
        lead: str,
        description: str = "",
        project_template_key: str | None = None,
    ) -> str: ...
    async def delete_project(self, *, project_id: str, project_key: str) -> None: ...
    async def update_project(
        self, project_id: str, *, name: str | None = None, lead: str | None = None, description: str | None = None
    ) -> None: ...

    # ── Issues (data plane) ──────────────────────────────────────────
    def search(self, *, jql: str, fields: list[str], page_size: int = 50) -> AsyncIterator[dict[str, Any]]: ...
    async def get_issue(self, key: str, *, fields: list[str]) -> dict: ...
    async def create_issue(self, body: dict[str, Any]) -> dict[str, Any]: ...
    async def update_issue(self, key: str, body: dict[str, Any]) -> None: ...
    async def delete_issue(self, key: str) -> None: ...
