#!/usr/bin/env python3
"""Offline repro: ``stint revision --autogenerate`` no longer leaks sibling
module's Project into the generated migration.

Demonstrates the fix for CMP-B in ``CMP_ISSUE_DRAFT.md`` (importing a
sibling schema module for reuse -- a documented pattern -- used to
register the sibling's ``Project`` as a side effect, and the
autogenerated migration would then reference it, reaching into an
unrelated live project). Pre-fix the autogenerated migration mentioned
both Projects; post-fix it mentions only the one declared in the
``--schema`` module.

Drives the in-process CLI ``main()`` directly with ``respx`` mocking
Jira, instead of shelling out (so the HTTP layer is also exercised).
Temporary schema files are written under a temp dir that's auto-cleaned.

Usage:
    uv run python tools/cmp_autogenerate_scoping_repro.py
"""

from __future__ import annotations

import os
import shutil
import sys
import tempfile
from pathlib import Path

import httpx
import respx

from stint import StateFile
from stint.cli.app import main as stint_main
from stint.registry import registry

BASE = "https://example.atlassian.net"
CLOUD_ROOT = f"{BASE}/rest/api/3"


SCHEMA_A_BODY = """\
from __future__ import annotations

import schema_b  # noqa: F401  -- reuse import; registers ProjB as a side effect

from stint import IssueType, Project


class TaskA(IssueType):
    __alias__ = "task_a"


class ProjA(Project):
    __key__ = "AAA"
    __style__ = "company-managed"
    __issuetypes__ = [TaskA]
"""


SCHEMA_B_BODY = """\
from __future__ import annotations

from stint import IssueType, Project


class TaskB(IssueType):
    __alias__ = "task_b"


class ProjB(Project):
    __key__ = "BBB"
    __style__ = "company-managed"
    __issuetypes__ = [TaskB]
"""


def _paginated(values: list) -> dict:
    return {"values": values, "isLast": True, "startAt": 0, "maxResults": len(values)}


def _stub_empty_jira(mock: respx.MockRouter) -> None:
    """All admin endpoints return empty -- Jira has nothing."""
    mock.get(f"{CLOUD_ROOT}/serverInfo").mock(
        return_value=httpx.Response(
            200,
            json={"baseUrl": BASE, "version": "9", "deploymentType": "Cloud"},
        )
    )
    mock.get(f"{CLOUD_ROOT}/field").mock(return_value=httpx.Response(200, json=[]))
    mock.get(f"{CLOUD_ROOT}/field/search").mock(return_value=httpx.Response(200, json=_paginated([])))
    mock.get(f"{CLOUD_ROOT}/issuetype").mock(return_value=httpx.Response(200, json=[]))
    for path in (
        "/project/search",
        "/screens",
        "/screenscheme",
        "/issuetypescheme",
        "/issuetypescheme/mapping",
        "/issuetypescheme/project",
        "/issuetypescreenscheme",
        "/issuetypescreenscheme/project",
        "/fieldconfiguration",
        "/fieldconfigurationscheme",
        "/fieldconfigurationscheme/project",
    ):
        mock.get(f"{CLOUD_ROOT}{path}").mock(return_value=httpx.Response(200, json=_paginated([])))


def main() -> int:
    registry.reset()
    # Drop any cached module so the fresh schema files import cleanly.
    sys.modules.pop("schema_a", None)
    sys.modules.pop("schema_b", None)
    sys.modules.pop("examples.company_managed.platform", None)
    # The CLI requires STINT_TOKEN; we set it to a stub since respx mocks
    # the actual HTTP calls.
    os.environ.setdefault("STINT_TOKEN", "tok")

    tmp_dir = Path(tempfile.mkdtemp(prefix="stint-scoping-"))
    try:
        (tmp_dir / "schema_a.py").write_text(SCHEMA_A_BODY)
        (tmp_dir / "schema_b.py").write_text(SCHEMA_B_BODY)
        (tmp_dir / "__init__.py").write_text("")

        mig_dir = tmp_dir / "migrations"
        mig_dir.mkdir()
        state_path = tmp_dir / "state.yaml"
        StateFile(env="dev", jira_url=BASE).save(state_path)

        sys.path.insert(0, str(tmp_dir))

        with respx.mock:
            _stub_empty_jira(respx.mock)
            rc = stint_main(
                [
                    "revision",
                    "--migrations-dir",
                    str(mig_dir),
                    "-m",
                    "scoped autogenerate",
                    "--autogenerate",
                    "--schema",
                    str(tmp_dir / "schema_a.py"),
                    "--state",
                    str(state_path),
                    "--env",
                    "dev",
                    "--url",
                    f"jira_cloud+{BASE}",
                    "--auth",
                    "pat",
                ]
            )

        if rc != 0:
            print(f"FAIL: stint revision returned exit code {rc}.")
            return rc

        mig_files = sorted(mig_dir.glob("*.py"))
        if len(mig_files) != 1:
            print(f"FAIL: expected 1 migration file, got {len(mig_files)}: {mig_files}")
            return 1
        source = mig_files[0].read_text()

        print("Generated migration:")
        print(source)
        print()

        # The post-fix contract: AAA appears, BBB does not.
        ok_aaa = "key='AAA'" in source
        ok_bbb = "key='BBB'" not in source
        ok_task_a = "alias='task_a'" in source
        ok_task_b = "alias='task_b'" not in source

        if not ok_aaa:
            print("FAIL: migration does not reference ProjA (key='AAA').")
            return 1
        if not ok_bbb:
            print("FAIL: migration references ProjB (key='BBB') -- sibling module leaked.")
            return 1
        if not ok_task_a:
            print("FAIL: migration does not reference task_a.")
            return 1
        if not ok_task_b:
            print("FAIL: migration references task_b -- sibling module's IssueType leaked.")
            return 1
        print("PASS: --schema module is the only source of Project + IssueType refs.")
        print("      ProjA 'AAA' present; sibling ProjB 'BBB' absent.")
        return 0
    finally:
        sys.path.remove(str(tmp_dir))
        shutil.rmtree(tmp_dir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
